some changes

diff --git a/cloudbuild.yml b/cloudbuild.yml
--- a/cloudbuild.yml
+++ b/cloudbuild.yml
@@ -4,16 +4,108 @@ substitutions:
   _IMAGE: 'nginx-app'
   _TAG: 'v1.01'
   _LOG_BUCKET: 'devops_ci_logs'
+  
+  # _IMAGE_NAME: '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}'
 
 steps:
+
+# Step 1: Build the image and save to a tarball (no push)
+- name: 'gcr.io/kaniko-project/executor:latest'
+  id: 'build-only'
+  args:
+    - --context=dir://app
+    - --no-push
+    - --tar-path=/workspace/image.tar
+    - --destination=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
+    - --cache=true
+    - --cache-ttl=168h
+    # Point this to a 'cache' folder in your repository
+    - --cache-repo=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/cache
+    - --reproducible=true
+
+# Step 2: Load image into Docker
+- name: 'gcr.io/cloud-builders/docker'
+  id: 'load-image'
+  args:
+    - 'load'
+    - '-i'
+    - '/workspace/image.tar'
+
 - name: gcr.io/google.com/cloudsdktool/cloud-sdk
   entrypoint: bash
   args:
   - '-c'
   - |
-    Digest_list=$(gcloud artifacts docker images list ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY} --format='get(DIGEST)')
+    gcloud artifacts docker images list ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY} --format='value(version)' > /workspace/digests.txt
+    
+    
+    cat /workspace/digests.txt
 
-    echo "Digest_list:"
-    echo "${Digest_list}"
+# Step 3: Push the tarball to the Artifact Registry
+
+- name: 'gcr.io/cloud-builders/docker'
+  id: 'conditional-push'
+  entrypoint: 'bash'
+  args:
+    - '-c'
+    - |
+      set -e
+      set -o pipefail
+
+      Target_Image=$$(docker images --format "{{.Digest}}" ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG})
+      
+      if [ -z "$$Target_Image" ]; then
+        echo "Failed to retrieve the target image digest. Please check if the image was built successfully."
+        exit 1
+      fi
+
+      found=false
+
+      images_in_repo=$$(cat /workspace/digests.txt)
+
+      if [ -z "$$images_in_repo" ]; then
+        echo "No images found in the repository. Pushing new image to Artifact Registry..."
+        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}"  
+      else
+
+      for img in $$images_in_repo; do
+        if [[ "$$img" == *"$$Target_Image"* ]]; then
+          echo "This image already exists in the local repository. Skipping push."
+          found=true
+          break
+        fi
+      done
+
+      if [ "$$found" = false ]; then
+        echo "Pushing new image to Artifact Registry..."        
+        docker push "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}"
+      fi
+
+# Step 4: List all images in the repository
+- name: 'gcr.io/cloud-builders/gcloud'
+  id: 'list-all-images'
+  args:
+  - 'artifacts'
+  - 'docker'
+  - 'images'
+  - 'list'
+  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}'
+
+
+# Step 5: Inspect the image to verify RootFS layers (Focusing on the layers list)
+- name: 'gcr.io/cloud-builders/docker'
+  id: 'inspect-image'
+  entrypoint: 'bash'
+  args:
+    - '-c'
+    - |
+      docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
+      echo "--- ROOTFS LAYERS ---"
+      docker inspect --format='{{json .RootFS.Layers}}' ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
+
+# Step 6: Run functional tests
+- name: 'gcr.io/cloud-builders/docker'
+  id: 'test-image'
+  args: ['run', '--rm', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}', 'echo', 'Tests passed']
 
 logsBucket: 'gs://${_LOG_BUCKET}'
