fix issue

diff --git a/cloudbuild.yml b/cloudbuild.yml
--- a/cloudbuild.yml
+++ b/cloudbuild.yml
@@ -48,6 +48,7 @@ steps:
 - name: 'alpine:latest'
   id: 'quality-gate'
   entrypoint: 'sh'
+  secretEnv: ['_SONAR_TOKEN']
   args:
     - '-c'
     - |
@@ -61,14 +62,13 @@ steps:
         echo "----------------------------------------------------------------------------------------------------------"
         
         # Keep your existing SonarQube curl script here, for example:
-        # STATUS=$(curl -s -u "$${SONAR_TOKEN}:" "http://your-sonar-server/api/qualitygates/project_status?projectKey=my-project" | jq -r '.projectStatus.status')
-        #
-        # echo "Quality Gate Status: $STATUS"
-        # if [ "$STATUS" != "OK" ]; then
-        #   echo "Quality Gate Failed"
-        #   exit 1
-        # fi
-
+        STATUS=$(curl -s -u "$${_SONAR_TOKEN}:" "http://${_SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=${_SONAR_PROJECT_KEY}" | jq -r '.projectStatus.status')
+        
+         echo "Quality Gate Status: $STATUS"
+         if [ "$$STATUS" != "OK" ]; then
+           echo "Quality Gate Failed"
+           exit 1
+         fi
 
 # Step 4: List all images currently in the repository and calculate the next semver tag
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
